const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const http = require('node:http');
const https = require('node:https');
const { execFileSync } = require('node:child_process');
(async () => {
  const profile = fs.mkdtempSync(path.join(os.tmpdir(),'dioptra-workspace-'));
  if(process.env.CLAUDE_TEST_EXTENSION_DIR) fs.cpSync(process.env.CLAUDE_TEST_EXTENSION_DIR,path.join(profile,'claude-extension'),{recursive:true});
  const serve = name => (req,res) => { if(req.url==='/cached')res.setHeader('Cache-Control','public, max-age=3600'); if(req.url==='/redirect'){res.writeHead(302,{Location:'/final'});return res.end();} if(req.url==='/slow'){res.setHeader('Content-Disposition','attachment; filename="slow.txt"');res.setHeader('Content-Length',1024*1024*4);let sent=0;const timer=setInterval(()=>{res.write(Buffer.alloc(65536));if(++sent===64){clearInterval(timer);res.end();}},30);res.on('close',()=>clearInterval(timer));return;} if(req.url==='/download'){res.setHeader('Content-Disposition','attachment; filename="sample.txt"');return res.end('download');} res.setHeader('Content-Type','text/html'); res.end(`<title>${name}</title><h1>${name}</h1><p>needle needle</p><a href="/next">Next</a>`); };
  const host=http.createServer(serve('HOSTFILE'));
  await new Promise(r=>host.listen(0,'::1',r));
  const port=host.address().port;
  const live=http.createServer(serve('LIVE'));
  await new Promise(r=>live.listen(port,'127.0.0.1',r));
  execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',path.join(profile,'key'),'-out',path.join(profile,'cert'),'-days','1','-subj','/CN=localhost'],{stdio:'ignore'});
  const tls=https.createServer({key:fs.readFileSync(path.join(profile,'key')),cert:fs.readFileSync(path.join(profile,'cert'))},serve('TLS'));
  await new Promise(r=>tls.listen(0,'::1',r));
  fs.writeFileSync(path.join(profile,'settings.json'),JSON.stringify({rules:[{domain:'localhost',ip:'::1',enabled:true}],tabs:[`http://localhost:${port}/`]}));
  let app;
  // Quit the way a user does (Cmd+Q -> app.quit) and require the process to exit; Playwright's close() can stall closing pages under Rosetta.
  const quit=async a=>{const exited=new Promise(r=>a.process().exitCode!==null?r():a.process().once('exit',r));await a.evaluate(({app})=>app.quit()).catch(()=>{});await Promise.race([exited,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Dioptra did not quit within 20 s')),20000))]);};
  const launch=()=>electron.launch({executablePath:process.env.DIOPTRA_TEST_EXECUTABLE||undefined,args:[...(process.getuid?.()===0?['--no-sandbox','-r',path.join(__dirname,'root-harness.cjs')]:[]),...(process.env.DIOPTRA_TEST_EXECUTABLE?[]:['.']),`--profile-dir=${profile}`],cwd:path.resolve(__dirname,'..')});
  try {
    app=await launch(); let ui=await app.firstWindow(); ui.setDefaultTimeout(15000); globalThis.lastUI=ui;
    const pollUI=async fn=>{const until=Date.now()+15000;while(Date.now()<until){if(await ui.evaluate(fn))return;await new Promise(r=>setTimeout(r,100));}throw new Error('State wait timed out: '+fn.toString());};
    const cmd=(action,data)=>ui.evaluate(([a,d])=>window.browser.command(a,d),[action,data]);
    await ui.waitForFunction(()=>window.browser);
    await pollUI(async()=>{const r=await window.browser.command('state');return r.state.tabs.some(t=>t.title==='HOSTFILE'&&!t.loading);});
    await app.evaluate(()=>process.getBuiltinModule('dns').setDefaultResultOrder('ipv4first'));
    const results=await Promise.all([cmd('compare'),cmd('compare')]); for(const result of results)assert.equal(result.ok,true,JSON.stringify(result));
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;return s.tabs.some(t=>t.title==='LIVE'&&!t.loading&&t.connection?.ip.includes('127.0.0.1'));});
    let s=(await cmd('state')).state;
    assert.ok(s.performance.memoryKB>0,'Actual browser process memory is sampled');
    assert.ok(s.performance.processes>0);
    assert.match(await ui.locator('#memory-usage').innerText(),/Dioptra RAM [\d.]+ [MG]B/);
    assert.ok(s.comparison,'comparison active');assert.equal(s.tabs.filter(t=>t.mode==='live').length,1,'double Compare creates only one Live tab');
    const mapped=s.tabs.find(t=>t.mode==='hostfile'); const normal=s.tabs.find(t=>t.mode==='live');
    assert.equal(mapped.connection.ip.replace(/^\[|\]$/g,''),'::1');
    assert.ok(normal.connection.ip.includes('127.0.0.1'),JSON.stringify(normal.connection));
    await ui.locator('#pane-bars').getByText('HOSTFILE',{exact:true}).waitFor();
    await ui.locator('#pane-bars').getByText('LIVE',{exact:true}).waitFor();
    assert.equal(await ui.locator('#pane-bars .route-bar').count(),2,'one route bar per compare pane');assert.equal(await ui.locator('#compare').getAttribute('aria-pressed'),'true');
    fs.mkdirSync('artifacts',{recursive:true});await ui.screenshot({path:'artifacts/workspace-compare.png'});
    const geometry=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].contentView.children.filter(v=>v.webContents.getURL().startsWith('http://localhost:')).map(v=>v.getBounds()));
    assert.equal(geometry.length,2); assert.ok(geometry[0].x+geometry[0].width<=geometry[1].x);
    await cmd('activate',normal.id); await cmd('navigate',`http://localhost:${port}/redirect`);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;return s.tabs.find(t=>t.id===s.activeId)?.url.endsWith('/final');});
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;const t=s.tabs.find(t=>t.id===s.activeId);return !t.loading&&t.connection?.url===t.url;});
    s=(await cmd('state')).state;assert.equal(s.tabs.find(t=>t.id===mapped.id).url,`http://localhost:${port}/`);
    assert.ok(s.tabs.find(t=>t.id===normal.id).connection.ip.includes('127.0.0.1'));
    const isolated=await app.evaluate(async({session},url)=>{await session.fromPartition('persist:web').cookies.set({url,name:'workspace',value:'host'});return session.fromPartition('live-comparison').cookies.get({url,name:'workspace'});},`http://localhost:${port}/`);assert.equal(isolated.length,0,'Live cookies isolated from Hostfile');
    await cmd('navigate','http://missing-workspace.invalid/');
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;return Boolean(s.tabs.find(t=>t.id===s.activeId)?.error);});
    s=(await cmd('state')).state;assert.equal(s.tabs.find(t=>t.id===normal.id).connection,null,'failure clears prior IP');
    await ui.locator('#comparison-errors').getByText('LIVE could not load').waitFor();
    await cmd('navigate',`http://localhost:${port}/final`);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;const t=s.tabs.find(t=>t.id===s.activeId);return !t.loading&&!t.error&&Boolean(t.connection?.ip);});
    await app.evaluate(({webContents,session})=>{const wc=webContents.getAllWebContents().find(w=>w.session===session.fromPartition('live-comparison'));wc.focus();wc.sendInputEvent({type:'keyDown',keyCode:'F',modifiers:[process.platform==='darwin'?'meta':'control']});wc.sendInputEvent({type:'keyUp',keyCode:'F',modifiers:[process.platform==='darwin'?'meta':'control']});}); await ui.getByLabel('Find in page',{exact:true}).fill('needle');
    await ui.waitForFunction(()=>document.querySelector('#find-count').textContent.includes('2'));
    const firstMatch=(await cmd('state')).state.find.active;await ui.getByRole('button',{name:'Next match',exact:true}).click();
    await pollUI(async()=>{const f=(await window.browser.command('state')).state.find;return f.matches===2&&f.active===2;});
    assert.equal(firstMatch,1);await ui.getByRole('button',{name:'Previous match',exact:true}).click();
    await pollUI(async()=>{const f=(await window.browser.command('state')).state.find;return f.active===1;});
    await ui.getByRole('button',{name:'Close find',exact:true}).click();
    if(process.env.CLAUDE_TEST_EXTENSION_DIR){
      await pollUI(async()=> (await window.browser.command('state')).state.claude.status==='ready');
      await app.evaluate(({session},dest)=>session.fromPartition('live-comparison').once('will-download',(_e,item)=>item.setSavePath(dest)),path.join(profile,'claude-live.txt'));
      await cmd('panel','claude');
      await ui.screenshot({path:'artifacts/workspace-compare-claude.png'});
      const id=await app.evaluate(({webContents},url)=>webContents.getAllWebContents().find(w=>w.getURL().includes('/sidepanel.html')).executeJavaScript('chrome.downloads.download('+JSON.stringify({url})+')'),`http://localhost:${port}/download`);assert.equal(typeof id,'number');
      await pollUI(async()=> (await window.browser.command('state')).state.library.downloads.some(d=>d.state==='completed'));
      assert.equal(fs.readFileSync(path.join(profile,'claude-live.txt'),'utf8'),'download');
    }
    await cmd('bookmark'); await cmd('panel','library');
    await ui.getByRole('button',{name:'Bookmarks',exact:true}).click();
    await ui.locator('#library-list').getByText(`http://localhost:${port}/final`,{exact:true}).waitFor();
    await cmd('panel',null);await cmd('activate',mapped.id);await cmd('close-tab',normal.id);
    s=(await cmd('state')).state;assert.equal(s.comparison,null);assert.equal(s.paneLayout.length,1,'closing inactive peer clears its banner');
    assert.ok(s.paneLayout[0].page.width>geometry[0].width,'remaining pane expands');
    await cmd('new-tab',`http://localhost:${port}/closed`);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;return s.tabs.find(t=>t.id===s.activeId)?.title==='HOSTFILE';});
    s=(await cmd('state')).state;await cmd('close-tab',s.activeId);await cmd('reopen-tab');
    s=(await cmd('state')).state;assert.ok(s.tabs.find(t=>t.id===s.activeId).url.endsWith('/closed'));
    await cmd('navigate',`https://localhost:${tls.address().port}/`);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;return s.tabs.find(t=>t.id===s.activeId)?.title==='TLS';});
    assert.equal((await cmd('ssl-verification',true)).ok,true);
    assert.equal((await cmd('state')).state.pending,true);await quit(app);app=null;app=await launch();ui=await app.firstWindow();ui.setDefaultTimeout(15000);globalThis.lastUI=ui;await ui.waitForFunction(()=>window.browser);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;return /CERT/.test(s.tabs.find(t=>t.id===s.activeId)?.error);});
    assert.equal((await cmd('ssl-verification',false)).ok,true);
    await quit(app);app=null;app=await launch();ui=await app.firstWindow();ui.setDefaultTimeout(15000);globalThis.lastUI=ui;await ui.waitForFunction(()=>window.browser);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;const t=s.tabs.find(t=>t.id===s.activeId);return t&&!t.error&&!t.loading&&t.title==='TLS';});
    await cmd('navigate',`http://localhost:${port}/`);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;return !s.tabs.find(t=>t.id===s.activeId)?.loading;});
    await app.evaluate(({session},dest)=>{session.fromPartition('persist:web').once('will-download',(_e,item)=>item.setSavePath(dest));},path.join(profile,'sample.txt'));
    await app.evaluate(({webContents},url)=>webContents.getAllWebContents().find(w=>w.getURL()===url).executeJavaScript("const a=document.createElement('a');a.href='/download';document.body.append(a);a.click()"),`http://localhost:${port}/`);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;return s.library.downloads.some(d=>d.state==='completed'&&d.path.endsWith('/sample.txt'));});
    assert.equal(fs.readFileSync(path.join(profile,'sample.txt'),'utf8'),'download');
    await cmd('panel','library');await ui.getByRole('button',{name:'Downloads',exact:true}).click();
    await app.evaluate(({session},dest)=>{session.fromPartition('persist:web').once('will-download',(_e,item)=>item.setSavePath(dest));},path.join(profile,'slow.txt'));
    await app.evaluate(({webContents},url)=>webContents.getAllWebContents().find(w=>w.getURL()===url).executeJavaScript("const b=document.createElement('a');b.href='/slow';document.body.append(b);b.click()"),`http://localhost:${port}/`);
    await ui.getByRole('button',{name:'Pause',exact:true}).click();
    await pollUI(async()=> (await window.browser.command('state')).state.downloads.some(d=>d.paused));
    await ui.getByRole('button',{name:'Resume',exact:true}).click();
    await ui.getByRole('button',{name:'Cancel',exact:true}).click();
    await pollUI(async()=> (await window.browser.command('state')).state.library.downloads.some(d=>d.name==='slow.txt'&&d.state==='cancelled'));
    await app.evaluate(({session},dest)=>{session.fromPartition('persist:web').once('will-download',(_e,item)=>item.setSavePath(dest));},path.join(profile,'blob.txt'));
    await app.evaluate(({webContents},url)=>webContents.getAllWebContents().find(w=>w.getURL()===url).executeJavaScript("const c=document.createElement('a');c.href=URL.createObjectURL(new Blob(['blob-content']));c.download='blob.txt';document.body.append(c);c.click()"),`http://localhost:${port}/`);
    await pollUI(async()=> (await window.browser.command('state')).state.library.downloads.some(d=>d.name==='blob.txt'&&d.state==='completed'));
    assert.equal(fs.readFileSync(path.join(profile,'blob.txt'),'utf8'),'blob-content');

    await cmd('navigate',`http://localhost:${port}/cached`);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;const t=s.tabs.find(t=>t.id===s.activeId);return !t.loading&&t.url.endsWith('/cached')&&Boolean(t.connection?.ip);});
    await cmd('navigate','about:blank');
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;const t=s.tabs.find(t=>t.id===s.activeId);return !t.loading&&t.url==='about:blank';});
    s=(await cmd('state')).state;assert.equal(s.tabs.find(t=>t.id===s.activeId).connection,null,'blank page clears previous IP');
    await cmd('navigate',`http://localhost:${port}/cached`);
    await pollUI(async()=>{const s=(await window.browser.command('state')).state;const t=s.tabs.find(t=>t.id===s.activeId);return !t.loading&&t.url.endsWith('/cached')&&t.connection?.fromCache;});
    s=(await cmd('state')).state;assert.equal(s.tabs.find(t=>t.id===s.activeId).connection.ip,'','cached response never presented as freshly measured IP');
    await cmd('panel','library'); await ui.getByRole('button',{name:'History',exact:true}).click();
    assert.ok((await cmd('state')).state.library.history.length>0);
    await cmd('clear-history');assert.equal((await cmd('state')).state.library.history.length,0);
    fs.mkdirSync('artifacts',{recursive:true});await ui.screenshot({path:'artifacts/workspace-library.png'});
    await quit(app);app=null;
    app=await launch();const ui2=await app.firstWindow();await ui2.waitForFunction(()=>window.browser);
    const restored=(await ui2.evaluate(()=>window.browser.command('state'))).state;
    assert.equal(restored.library.bookmarks.length,1);assert.ok(restored.library.downloads.some(d=>d.state==='completed'));assert.equal(restored.sslVerification,false);
    console.log('PASS comparison distinct actual IPs, native routing, independent redirect, banners, find, bookmarks, reopen, TLS switch, downloads, history, persistence');
  } catch(error) { console.error('Workspace state',JSON.stringify(globalThis.lastUI ? await globalThis.lastUI.evaluate(()=>window.browser.command('state')).catch(()=>null) : null)); throw error; } finally {if(app)await quit(app);for(const server of [host,live,tls]){server.closeAllConnections();server.close();}fs.rmSync(profile,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exit(1);});
